# Generated by Django 4.1.7 on 2023-03-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_feeding'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dog',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='feeding',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='feeding',
            name='date',
            field=models.DateField(verbose_name='feeding date'),
        ),
        migrations.CreateModel(
            name='Toy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('color', models.CharField(choices=[('B', 'Blue'), ('Y', 'Yellow'), ('P', 'Purple'), ('R', 'Red'), ('G', 'Green')], default='B', max_length=10)),
                ('dogs', models.ManyToManyField(to='main_app.dog')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
