# Generated by Django 4.1.7 on 2023-03-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_dog_options_alter_feeding_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toy',
            name='dogs',
        ),
        migrations.AddField(
            model_name='toy',
            name='toys',
            field=models.ManyToManyField(to='main_app.dog'),
        ),
    ]
