# Generated by Django 4.1.7 on 2023-03-29 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_toy_dogs_toy_toys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toy',
            name='toys',
        ),
        migrations.AddField(
            model_name='toy',
            name='dogs',
            field=models.ManyToManyField(to='main_app.dog'),
        ),
    ]
