# Generated by Django 4.1.7 on 2023-03-29 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_toy_toys_toy_dogs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toy',
            name='dogs',
        ),
        migrations.AddField(
            model_name='dog',
            name='toys',
            field=models.ManyToManyField(to='main_app.toy'),
        ),
    ]
